# Generated by Django 4.1 on 2023-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OANDA_Request_Paramaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FX_Pair', models.CharField(default='USD_CAD', max_length=7)),
                ('Start_Date', models.DateTimeField()),
                ('Granularity', models.CharField(default='M2', max_length=2)),
                ('End_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
