# Generated by Django 4.1 on 2023-11-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oanda_request_paramaters',
            name='End_Date',
            field=models.DateTimeField(),
        ),
    ]
