# Generated by Django 4.1 on 2023-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_oanda_request_paramaters_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oanda_request_paramaters',
            name='FX_Pair',
            field=models.CharField(choices=[('GBP_SGD', 'GBP_SGD'), ('USD_SEK', 'USD_SEK'), ('EUR_DKK', 'EUR_DKK'), ('CAD_CHF', 'CAD_CHF'), ('USD_CZK', 'USD_CZK'), ('USD_ZAR', 'USD_ZAR'), ('USD_DKK', 'USD_DKK'), ('GBP_USD', 'GBP_USD'), ('USD_MXN', 'USD_MXN'), ('USD_HUF', 'USD_HUF'), ('EUR_CAD', 'EUR_CAD'), ('EUR_USD', 'EUR_USD'), ('CAD_JPY', 'CAD_JPY'), ('NZD_HKD', 'NZD_HKD'), ('USD_HKD', 'USD_HKD'), ('AUD_JPY', 'AUD_JPY'), ('ZAR_JPY', 'ZAR_JPY'), ('GBP_ZAR', 'GBP_ZAR'), ('SGD_JPY', 'SGD_JPY'), ('USD_JPY', 'USD_JPY'), ('EUR_TRY', 'EUR_TRY'), ('EUR_JPY', 'EUR_JPY'), ('AUD_SGD', 'AUD_SGD'), ('EUR_NZD', 'EUR_NZD'), ('GBP_HKD', 'GBP_HKD'), ('CHF_JPY', 'CHF_JPY'), ('EUR_HKD', 'EUR_HKD'), ('GBP_CAD', 'GBP_CAD'), ('USD_THB', 'USD_THB'), ('GBP_CHF', 'GBP_CHF'), ('AUD_CHF', 'AUD_CHF'), ('NZD_CHF', 'NZD_CHF'), ('AUD_HKD', 'AUD_HKD'), ('USD_CHF', 'USD_CHF'), ('CAD_HKD', 'CAD_HKD'), ('AUD_CAD', 'AUD_CAD'), ('GBP_PLN', 'GBP_PLN'), ('EUR_PLN', 'EUR_PLN'), ('GBP_NZD', 'GBP_NZD'), ('EUR_HUF', 'EUR_HUF'), ('EUR_NOK', 'EUR_NOK'), ('CHF_HKD', 'CHF_HKD'), ('EUR_GBP', 'EUR_GBP'), ('AUD_NZD', 'AUD_NZD'), ('CAD_SGD', 'CAD_SGD'), ('EUR_CZK', 'EUR_CZK'), ('NZD_JPY', 'NZD_JPY'), ('USD_TRY', 'USD_TRY'), ('GBP_JPY', 'GBP_JPY'), ('SGD_CHF', 'SGD_CHF'), ('USD_CNH', 'USD_CNH'), ('USD_NOK', 'USD_NOK'), ('NZD_SGD', 'NZD_SGD'), ('NZD_USD', 'NZD_USD'), ('USD_CAD', 'USD_CAD'), ('AUD_USD', 'AUD_USD'), ('CHF_ZAR', 'CHF_ZAR'), ('HKD_JPY', 'HKD_JPY'), ('EUR_SEK', 'EUR_SEK'), ('USD_SGD', 'USD_SGD'), ('TRY_JPY', 'TRY_JPY'), ('NZD_CAD', 'NZD_CAD'), ('EUR_SGD', 'EUR_SGD'), ('EUR_AUD', 'EUR_AUD'), ('GBP_AUD', 'GBP_AUD'), ('USD_PLN', 'USD_PLN'), ('EUR_CHF', 'EUR_CHF'), ('EUR_ZAR', 'EUR_ZAR')], default='USD_CAD', max_length=7),
        ),
        migrations.AlterField(
            model_name='oanda_request_paramaters',
            name='Granularity',
            field=models.CharField(choices=[('S5', '5 second'), ('S10', '10 second'), ('S15', '15 second'), ('S30', '30 second'), ('M1', '1 minute'), ('M2', '2 minute'), ('M4', '4 minute'), ('M5', '5 minute'), ('M10', '10 minute'), ('M15', '15 minute'), ('M30', '30 minute'), ('H1', '1 hour'), ('H2', '2 hour'), ('H3', '3 hour'), ('H4', '4 hour'), ('H6', '6 hour'), ('H8', '8 hour'), ('H12', '12 hour'), ('D', '1 day'), ('W', '1 week'), ('M', '1 month')], default='M2', max_length=9),
        ),
    ]
